name: eyescandrive
description: "EyeScanDrive - Sistema de asistencia de conducción con detección de somnolencia por IA"

publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.29.0
  permission_handler: ^11.3.1
  battery_plus: ^5.0.3
  just_audio: ^0.9.36
  audioplayers: ^6.1.0
  geolocator: ^10.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.0.0
  shared_preferences: ^2.0.18
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.4
  camera: ^0.10.5+5
  tflite_flutter: ^0.11.0
  onnxruntime: ^1.4.1
  image: ^4.1.3
  path_provider: ^2.1.1
  flutter_tts: ^4.0.2
  fl_chart: ^0.66.0
  uuid: ^4.2.1
  postgres: ^3.0.0  # Base de datos PostgreSQL

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/labels/
    - assets/icons/
    - assets/sounds/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color: "#0F3460"
  adaptive_icon_background: "#0F3460"
  adaptive_icon_foreground: "assets/icons/icon.png"
